name: Windows Rtools40

on:
  push:
    branches: [ win-timing-test ]

jobs:
  timing-test:
    name: Timing test
    runs-on: windows-latest

    steps:
    - name: Timing for UCRT check
      if: runner.os == 'Windows'
      run: |
        Measure-Command { echo "#include <_mingw.h>" | g++ -E -dM -  | findstr /l _UCRT }
      shell: powershell

